"""add_document_chunks

Revision ID: 52c93bc841a7
Revises: 7cc6286570a5
Create Date: 2025-03-16 13:08:52.792437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '52c93bc841a7'
down_revision: Union[str, None] = '7cc6286570a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.add_column('documents', sa.Column('title', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('google_file_id', sa.String(), nullable=True))
    op.alter_column('documents', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_documents_file_id', table_name='documents')
    op.drop_index('ix_documents_name', table_name='documents')
    op.create_index(op.f('ix_documents_google_file_id'), 'documents', ['google_file_id'], unique=True)
    op.drop_column('documents', 'name')
    op.drop_column('documents', 'last_synced')
    op.drop_column('documents', 'file_id')
    op.drop_column('documents', 'doc_metadata')
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.add_column('documents', sa.Column('doc_metadata', sqlite.JSON(), nullable=True))
    op.add_column('documents', sa.Column('file_id', sa.VARCHAR(), nullable=True))
    op.add_column('documents', sa.Column('last_synced', sa.DATETIME(), nullable=True))
    op.add_column('documents', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_documents_google_file_id'), table_name='documents')
    op.create_index('ix_documents_name', 'documents', ['name'], unique=False)
    op.create_index('ix_documents_file_id', 'documents', ['file_id'], unique=1)
    op.alter_column('documents', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('documents', 'google_file_id')
    op.drop_column('documents', 'title')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
